NUM_OF_CARS = 100
MAX_MOVE = 10
NUM_OF_ROWS = 10
NUM_OF_COLS = 10
FIRST_ROW_INDEX = 0  # 0 or 1
FIRST_COL_INDEX = 0
LAST_ROW_INDEX = NUM_OF_ROWS + FIRST_ROW_INDEX - 1
LAST_COL_INDEX = NUM_OF_COLS + FIRST_COL_INDEX - 1

MOVE_DIR_COUNT = 8  # 4 or 8
BORDER_BEHAVIOR = "restricted"  # "restricted" or "not-restricted"
ALLOW_STANDING = False  # True or False
